services:
  - type: web
    name: personal-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_PATH
        value: /data/blog.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true
