services:
  - type: web
    name: personal-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      flask db upgrade &&
      gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DATABASE_URL
        value: sqlite:///blog.db
      - key: ADMIN_PASSWORD
        value: MySecureAdminPass123
      - key: ADMIN_TOKEN
        value: dd569d0d1e0926a49dba1409f4ccf54179c36ddfa6aadf08b877d447b662bce7
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true
