services:
  - type: web
    name: personal-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      flask db upgrade &&
      gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DATABASE_URL
        value: sqlite:///blog.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true
